"""add not-empty check for todos.name

Revision ID: 054c8e0cf6df
Revises: 998b4b3dea74
Create Date: 2025-08-14 10:45:03.852252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054c8e0cf6df'
down_revision = '998b4b3dea74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
